version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: geoip-app
    container_name: geoip-app
    restart: "no"
    ports:
      - "8060:80"
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - ASSET_URL=${ASSET_URL}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - ASN_DB_PATH=${ASN_DB_PATH}
      - CITY_DB_PATH=${CITY_DB_PATH}
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.5
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_INITDB_SKIP_TZINFO=1
      - CHARACTER_SET_SERVER=utf8
      - COLLATION_SERVER=utf8_general_ci
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8', '--collation-server=utf8_general_ci']


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"