version: '3'

services:
  geoip-app:
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"]
      interval: 1m
      timeout: 10s
      retries: 3
    environment:
      - MMDB_SYNC_PAT=${MMDB_SYNC_PAT}
